# Generated by Django 3.1.4 on 2021-01-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.CharField(max_length=250)),
                ('event_venue', models.CharField(max_length=50)),
                ('regn_fees', models.FloatField()),
                ('event_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
