# Generated by Django 3.1.4 on 2021-01-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_participents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Participents',
            new_name='Participent',
        ),
    ]
