# Generated by Django 3.1.4 on 2021-01-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_participent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participent',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='participent',
            name='year',
            field=models.IntegerField(),
        ),
    ]
